### ISSUE TITLE
How fast should the client issue requests?

### ISSUE THREAD

**Issue by derek1906** [summertriangle-dev/arposandra#33]
To avoid overloading the server, how fast should the client issue requests? Specifically, will the server return a 429 with `Retry-After` set so that the client can know how much time to wait before issuing the next request?

**Comment by summertriangle-dev** [comment]
The server currently doesn't enforce any rate limits. 

If your requests are all user-triggered then don't worry about limiting them on your end for now. If you need to make many requests in a short span of time (e.g. pulling the entire database on a schedule) then restricting that to once an hour is fine.

**Comment by derek1906** [comment]
I see, thanks!
