### ISSUE TITLE
Levels & Stats are incorrect

### ISSUE THREAD

**Issue by alantsin** [summertriangle-dev/arposandra#4]
Ever since the version 1.7 update of All Stars, the database has been displaying the base stats of all cards to be Lv. 100. Even with the new Kizuna Board mechanics, Lv. 100 is impossible to reach for a UR.

It would be better if the numbers were reverted to the Lv. 40, 60, and 80 maximum for R, SR, and UR cards respectively. Since Lv. 100 is not possible at this time, it makes using these numbers for reference meaningless and doesn't really help players.

**Comment by summertriangle-dev** [comment]
Thanks for reporting. I've fixed this in ce986fa.
